### ISSUE TITLE
Code becomes messy when changing code in VSCODE Macos.

### ISSUE THREAD

**Issue by ardhichoiruddin** [movebit/sui-move-analyzer#2]
Code becomes messy when changing code in VSCODE Macos.

https://github.com/user-attachments/assets/f1320db5-6046-4525-9898-90d90363d8d7

VsCode: 1.94.2
sui-move-analyzer VsCode: v1.1.6
sui-move-analyzer Server: 1.1.8
Os: MacOs 15.0

**Comment by hapeeeeee** [comment]
We have identified the issue and will resolve it in the next version.

**Comment by hapeeeeee** [comment]
We have fix this issue in [5e9c2deba1f23e1fcb83f4f3b098fe05e5da835b](https://github.com/movebit/sui-move-analyzer/commit/5e9c2deba1f23e1fcb83f4f3b098fe05e5da835b)
